// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvcwebapplication.Dao;

namespace mvcwebapplication.Migrations
{
    [DbContext(typeof(MvcWebApplicationDbContext))]
    [Migration("20200902164341_InitialAuthorAndBlog")]
    partial class InitialAuthorAndBlog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("mvcwebapplication.Models.Author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("fName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("mvcwebapplication.Models.BlogPost", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Authorid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("id");

                    b.HasIndex("Authorid");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("mvcwebapplication.Models.BlogPost", b =>
                {
                    b.HasOne("mvcwebapplication.Models.Author", null)
                        .WithMany("BlogPosts")
                        .HasForeignKey("Authorid");
                });
#pragma warning restore 612, 618
        }
    }
}
